# Generated by Django 3.2 on 2021-05-02 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('just_co_away', '0014_listing_date_verified_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(default='N/A', max_length=200)),
                ('available', models.BooleanField()),
                ('price', models.CharField(default='N/A', max_length=500)),
                ('phone_number', models.CharField(default='N/A', max_length=300)),
                ('whatsapp_number', models.CharField(default='N/A', max_length=300)),
                ('address', models.CharField(default='N/A', max_length=400)),
                ('state', models.CharField(default='N/A', max_length=200)),
                ('city', models.CharField(default='N/A', max_length=100)),
                ('pincode', models.CharField(default='N/A', max_length=100)),
                ('delivery', models.BooleanField()),
                ('maximum_delivery_distance', models.CharField(default='N/A', max_length=300)),
                ('date_verified_on', models.DateField()),
                ('verified_on', models.TimeField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-date_verified_on', '-verified_on'),
            },
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ('-date_verified_on', '-verified_on')},
        ),
    ]
